name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  image_picker: ^1.0.5
  file_picker: ^8.1.4
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  rename_app: ^1.6.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon-android.png"
  adaptive_icon_background: "#4A606B"
  adaptive_icon_foreground: "assets/images/icon-android.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png